services:
  - type: web
    name: betrix-ui
    env: node
    buildCommand: npm install
    startCommand: node index.js
    plan: free
    region: oregon
    branch: main
    repo: https://github.com/maryreaky/betrix-ui
