name: Unset Telegram Webhook
on:
  workflow_dispatch:

jobs:
  unset:
    runs-on: ubuntu-latest
    steps:
      - name: Unset webhook
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: |
          set -e
          echo "Calling Telegram to unset webhook..."
          curl -s "https://api.telegram.org/bot${TELEGRAM_TOKEN}/setWebhook?url=" | tee result.json
          cat result.json
